### ISSUE TITLE
No module named 'lib.models.hiptrack.DCPT

### ISSUE THREAD

**Issue by huang513589915** [OpenCodeGithub/H-DCPT#2]
Traceback (most recent call last):
  File "/home/lsw/HL/targettracking/H-DCPT-main/lib/train/run_training.py", line 109, in <module>
    main()
  File "/home/lsw/HL/targettracking/H-DCPT-main/lib/train/run_training.py", line 101, in main
    run_training(args.script, args.config, cudnn_benchmark=args.cudnn_benchmark,
  File "/home/lsw/HL/targettracking/H-DCPT-main/lib/train/run_training.py", line 72, in run_training
    expr_module = importlib.import_module('lib.train.train_script')
  File "/home/lsw/miniconda3/envs/ostrack/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lsw/HL/targettracking/H-DCPT-main/lib/train/../../lib/train/train_script.py", line 14, in <module>
    from lib.models.hiptrack import build_hiptrack
  File "/home/lsw/HL/targettracking/H-DCPT-main/lib/train/../../lib/models/__init__.py", line 1, in <module>
    from .hiptrack.hiptrack import build_hiptrack
  File "/home/lsw/HL/targettracking/H-DCPT-main/lib/train/../../lib/models/hiptrack/__init__.py", line 1, in <module>
    from .hiptrack import build_hiptrack
  File "/home/lsw/HL/targettracking/H-DCPT-main/lib/train/../../lib/models/hiptrack/hiptrack.py", line 14, in <module>
    from lib.models.hiptrack.DCPT import DCPT
ModuleNotFoundError: No module named 'lib.models.hiptrack.DCPT'

Process finished with exit code 1

**Comment by huang513589915** [comment]
我没在源码找到这个模块DCPT，这错误怎么解决啊

**Comment by OpenCodeGithub** [comment]
缺少的代码已上传，代码可以正常运行
